### ISSUE TITLE
Publish gem update to rubygems.org?

### ISSUE THREAD

**Issue by patrickatroli** [gaffneyc/sunspot-queue#24]
Hey,

Loving sunspot-queue, not loving how recent changes (in particular ReneB's [compatibility restore](3785398005465ed6738b7a3168defa96f86ee697) aren't yet available on rubygems. Any chance you could publish a new version? Life get *so* much easier if gems are available in the default source.

Ta!

**Comment by lmars** [comment]
:+1: it would be great to see 3785398 in a release

**Comment by gaffneyc** [comment]
@patrickatroli @lmars just pushed the changes to rubygems as `0.10.3`. Thanks for pushing on this and sorry it's taken so long.

**Comment by lmars** [comment]
Thanks!
